"""UEFA club competition results: the only place our five leagues actually meet.

Every prediction this project makes is within one league, because every match it
has ever seen is. That is invisible until something asks a cross-league
question, and two things now do: ``POST /predict`` will happily score Real
Madrid against Manchester City, and the League Strength panel asserts the
Premier League rates 3.6 higher per club than Ligue 1.

Neither has ever been checked against a result, and one of them cannot be from
domestic data alone. Elo makes the problem concrete: :mod:`footballml.features.elo`
keeps a single global ratings dict, but its updates are zero-sum and no match
crosses a league, so the five divisions are five disconnected pools each
anchored at 1500. Measured mean pre-match Elo in 2026/27 -- E0 1521, F1 1519,
I1 1519, D1 1514, SP1 1504 -- is a 17-point spread, which is noise. Elo cannot
tell a Bundesliga 1700 from a La Liga 1700.

European ties are the only evidence that can, so this module fetches them.

**Scope: big five against big five only.** A tie against Ajax or Benfica is
dropped. Those clubs have no squad rating, no form history and no canonical
name here -- ``config/team_aliases.yaml`` is generated by
``pipelines/derive_aliases.py``, which derives mappings by matching *domestic*
fixtures and so can only ever name clubs from the five leagues.

**These matches are evidence, not history.** Nothing here is appended to
``team_match_history_all.csv``. Feeding them into the rolling windows would
change every downstream feature and mean measuring a different model from the
one deployed. They are fixtures to be predicted, and
``pipelines/validate_european.py`` treats them as such.
"""

from __future__ import annotations

import logging

import pandas as pd

from footballml.entities.teams import load_aliases
from footballml.ingest.schedule import _SCORE

logger = logging.getLogger(__name__)

#: Our competition codes to soccerdata league keys. The keys are ours to choose:
#: soccerdata ships no UEFA club competitions in its built-in ``LEAGUE_DICT``,
#: so :func:`_register` adds them at run time.
EUROPEAN_LEAGUES = {
    "UCL": "UEFA-Champions League",
    "UEL": "UEFA-Europa League",
    "UECL": "UEFA-Conference League",
}

#: Which competitions the site shows fixtures for. Champions League only, and
#: that is a measurement rather than a preference: a tie is predictable only
#: when *both* clubs are from the big five, which is 41% of UCL matches against
#: 14% of Europa and 6% of Conference. A fixture list that is 86-94% holes is
#: worse than not having one. The other two are still fetched -- they feed the
#: cross-league correction -- they are just not put on the page.
SHOWN_COMPETITIONS = ("UCL",)

#: FBref's own name for each competition, exactly as its ``/en/comps/`` index
#: lists it. The competition ids are 8, 19 and 882 -- note 181 is the *Women's*
#: Champions League, which is why these are pinned by exact name rather than by
#: anything fuzzier.
_FBREF_NAMES = {
    "UCL": "UEFA Champions League",
    "UEL": "UEFA Europa League",
    "UECL": "UEFA Conference League",
}

#: Clubs whose European-page spelling the generated alias map does not cover.
#:
#: ``config/team_aliases.yaml`` is produced by ``pipelines/derive_aliases.py``,
#: which matches *domestic* fixtures and says in its header not to edit it by
#: hand -- so the supplement lives here, beside the only code that needs it.
#:
#: Found rather than guessed: every one of the 127 unresolved club names was
#: stripped of club-name affixes (FC, BSC, 05, Calcio...) and collapsed onto the
#: canonical list. Exactly one collided -- FBref's European pages say
#: "Hertha BSC" where football-data.co.uk says "Hertha". Hertha were relegated
#: after 2022/23, which is why the derivation never produced the mapping.
#:
#: **Re-run that check when seasons are added** rather than trusting this list;
#: a club missing here is discarded in silence.
EUROPEAN_ALIASES = {"Hertha BSC": "Hertha"}

#: Squad strength is joined from the *previous* season and ``team_strength.csv``
#: starts at 1516, so a 1516 European match has no strength on either side.
#: Starting at 1617 keeps every fetched row scorable.
FIRST_SEASON = "1617"

_OUT_COLUMNS = [
    "League", "Season", "Date", "HomeTeam", "AwayTeam",
    "FTHG", "FTAG", "FTR", "Round", "home_league", "away_league",
]

#: Rounds played over two legs. The second leg is not an independent match --
#: a side three up rests players, a side three down chases -- so these are the
#: rows most likely to behave unlike the domestic football the model learned.
#: Carried so the validation can report with and without them rather than
#: assuming either way.
TWO_LEGGED = (
    "Round of 32", "Round of 16", "Quarter-finals", "Semi-finals",
    "Knockout phase play-offs", "Knockout round play-offs", "Play-off round",
)

#: Single match at a neutral ground, so the home-advantage term is wrong for it.
#: One per competition per season, but worth being able to exclude.
NEUTRAL = ("Final",)

#: Single-leg round-robin: "Group stage" up to 2023/24, "League phase" after the
#: 2024/25 format change. The closest thing to domestic football in the data,
#: and so the fairest test of a model trained on it.
ROUND_ROBIN = ("Group stage", "League phase")


def classify_round(name: object) -> str:
    """``"round_robin"``, ``"two_legged"``, ``"neutral"`` or ``"unclassified"``.

    Returning a label for the unknown case rather than raising is deliberate:
    UEFA renames its rounds every few years -- "Group stage" became "League
    phase" in 2024/25 -- and a new label should show up as a visible bucket in
    the report, not crash a ninety-minute run or, worse, get quietly counted as
    round-robin football.
    """
    text = str(name)
    if text in ROUND_ROBIN:
        return "round_robin"
    if text in TWO_LEGGED:
        return "two_legged"
    if text in NEUTRAL:
        return "neutral"
    return "unclassified"


def _empty() -> pd.DataFrame:
    return pd.DataFrame(columns=_OUT_COLUMNS)


def _register(competitions: list[str]) -> None:
    """Teach soccerdata about the UEFA competitions, in this process only.

    ``soccerdata._config`` merges ``~/soccerdata/config/league_dict.json`` at
    import if that file exists. Updating the dict in memory instead keeps the
    repo self-contained: a fresh checkout on another machine needs no
    hand-written config file before the pipeline will run.
    """
    from soccerdata import _config

    for code in competitions:
        _config.LEAGUE_DICT.setdefault(
            EUROPEAN_LEAGUES[code],
            {"FBref": _FBREF_NAMES[code], "season_start": "Aug", "season_end": "May"},
        )


def fetch_european_matches(
    seasons: list[str], competitions: list[str] | None = None
) -> pd.DataFrame:
    """Played UEFA club matches, in the wide shape ``to_matches`` produces.

    Args:
        seasons: Four-digit labels, e.g. ``["2324", "2425"]``.
        competitions: Subset of :data:`EUROPEAN_LEAGUES`. Defaults to all three.

    Returns:
        ``League`` (``UCL``/``UEL``/``UECL``), ``Season``, ``Date``,
        ``HomeTeam``, ``AwayTeam``, ``FTHG``, ``FTAG``, ``FTR``, plus empty
        ``home_league``/``away_league`` for :func:`big_five_only` to fill.
        Unplayed fixtures are dropped. Empty if soccerdata is not installed --
        it lives in the optional ``ingest`` extra, so callers degrade rather
        than crash.
    """
    codes = list(competitions or EUROPEAN_LEAGUES)

    try:
        import soccerdata as sd
    except ImportError:  # pragma: no cover - depends on the optional extra
        logger.warning("soccerdata not installed; no European matches available")
        return _empty()

    _register(codes)
    aliases = {**load_aliases("fbref"), **EUROPEAN_ALIASES}
    frames = []

    for code in codes:
        # One competition-season at a time. Asking for a whole range in one call
        # loses every season to a single bad one, and bad ones are expected: the
        # Conference League did not exist before 2021/22, and 2019/20 finished
        # in August under a format nobody had used before.
        blocks = []
        for season in seasons:
            try:
                reader = sd.FBref(leagues=[EUROPEAN_LEAGUES[code]], seasons=[season])
                block = reader.read_schedule().reset_index()
            except Exception as exc:  # noqa: BLE001 - one bad season is survivable
                logger.warning("%s %s: could not read schedule (%s)", code, season, exc)
                continue
            if block.empty:
                logger.info("%s %s: no fixtures (competition may not have existed)", code, season)
                continue
            blocks.append(block)

        if not blocks:
            logger.warning("%s: nothing fetched for any season", code)
            continue
        raw = pd.concat(blocks, ignore_index=True)

        goals = raw["score"].astype(str).str.extract(_SCORE)
        frame = pd.DataFrame(
            {
                "League": code,
                "Season": raw["season"].astype(str),
                "Date": pd.to_datetime(raw["date"], errors="coerce").dt.normalize(),
                "HomeTeam": raw["home_team"].astype(str).str.strip().replace(aliases),
                "AwayTeam": raw["away_team"].astype(str).str.strip().replace(aliases),
                "FTHG": pd.to_numeric(goals[0], errors="coerce"),
                "FTAG": pd.to_numeric(goals[1], errors="coerce"),
                # "League phase", "Round of 16", "Final"... FBref labels every
                # match with its round, which is the only handle we have on the
                # two-legged and neutral-venue confounds.
                "Round": raw.get("round", pd.Series(pd.NA, index=raw.index)).astype("string"),
            }
        )
        played = frame["FTHG"].notna() & frame["FTAG"].notna() & frame["Date"].notna()
        logger.info(
            "%s: %d played across %d season(s); %d unplayed or undated, dropped",
            code, int(played.sum()), frame["Season"].nunique(), int((~played).sum()),
        )
        frames.append(frame[played])

    if not frames:
        return _empty()

    out = pd.concat(frames, ignore_index=True)
    home, away = out["FTHG"], out["FTAG"]
    out["FTR"] = pd.Series("D", index=out.index).mask(home > away, "H").mask(away > home, "A")
    out["home_league"] = pd.NA
    out["away_league"] = pd.NA
    return (
        out[_OUT_COLUMNS]
        .sort_values(["Date", "League", "HomeTeam"])
        .reset_index(drop=True)
    )


def big_five_only(
    matches: pd.DataFrame, tmh: pd.DataFrame
) -> tuple[pd.DataFrame, pd.DataFrame]:
    """Split into the matches we can score and the ones we cannot.

    A match is keepable only when *both* clubs played in one of the five leagues
    **in that same season**. Same-season matters: form comes from that season's
    domestic matches and strength from the season before, so a club that has
    dropped out of the big five but is still in Europe has neither.

    Returns:
        ``(kept, dropped)``. ``kept`` has ``home_league`` and ``away_league``
        filled with the clubs' domestic divisions, which is what the
        league-strength fit is built on. ``dropped`` carries a ``reason``.

        **Read the dropped list.** The alias map is derived from domestic
        fixtures only, so a big-five club spelled a new way on a European page
        is discarded in silence -- and a missing Real Madrid looks exactly like
        a correctly dropped Benfica. :func:`unmatched_clubs` is the review list.
    """
    if matches.empty:
        return _empty(), _empty().assign(reason=pd.Series(dtype="object"))

    lookup = (
        tmh[["Season", "Team", "League"]]
        .assign(Season=lambda d: d["Season"].astype(str))
        .drop_duplicates(subset=["Season", "Team"])
        .set_index(["Season", "Team"])["League"]
    )

    out = matches.copy()
    out["Season"] = out["Season"].astype(str)
    for side, column in (("HomeTeam", "home_league"), ("AwayTeam", "away_league")):
        out[column] = pd.MultiIndex.from_arrays([out["Season"], out[side]]).map(lookup)

    keep = out["home_league"].notna() & out["away_league"].notna()
    dropped = out[~keep].copy()
    dropped["reason"] = [
        "neither club in the big five this season"
        if pd.isna(h) and pd.isna(a)
        else f"away club {away!r} not in the big five this season"
        if pd.isna(a)
        else f"home club {home!r} not in the big five this season"
        for h, a, home, away in zip(
            dropped["home_league"], dropped["away_league"],
            dropped["HomeTeam"], dropped["AwayTeam"], strict=True,
        )
    ]

    logger.info(
        "Big five vs big five: kept %d of %d (%d dropped)",
        int(keep.sum()), len(out), int((~keep).sum()),
    )
    return out[keep].reset_index(drop=True), dropped.reset_index(drop=True)


def unmatched_clubs(dropped: pd.DataFrame) -> pd.Series:
    """Club names that caused a drop, most frequent first -- the review list.

    A name near the top with many appearances that *looks* like a big-five club
    is an alias gap, not a foreign side.
    """
    if dropped.empty:
        return pd.Series(dtype="int64")
    names = pd.concat(
        [
            dropped.loc[dropped["home_league"].isna(), "HomeTeam"],
            dropped.loc[dropped["away_league"].isna(), "AwayTeam"],
        ]
    )
    return names.value_counts()
