"""Derive team-name aliases by matching fixtures, not by matching strings.

Fuzzy string matching is the obvious approach and a bad one: ``Real Betis`` and
``Real Madrid`` are close neighbours, and a single wrong mapping silently
corrupts every join downstream.

Instead this matches on what the two sources agree about -- the fixtures
themselves. Within one league-season, a ``(date, home goals, away goals)``
triple almost always identifies exactly one match. Joining on that triple pairs
the two sources' names for the same club directly, with no guessing.

A name is only accepted when the evidence is unambiguous: it must appear in
several matched fixtures and agree in nearly all of them. Anything weaker is
reported for a human to resolve rather than written out.

Run with::

    python -m pipelines.derive_aliases
    python -m pipelines.derive_aliases --write
"""

from __future__ import annotations

import argparse
import logging
import sys
from collections import Counter, defaultdict
from pathlib import Path

import pandas as pd
import yaml

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))

from footballml.entities.teams import ALIAS_CONFIG  # noqa: E402
from footballml.ingest.matchhistory import fetch_match_history, to_matches  # noqa: E402
from footballml.ingest.understat import UNDERSTAT_LEAGUES, season_labels  # noqa: E402

HEADER = """\
# Canonical team names and their per-source aliases.
#
# GENERATED by `python -m pipelines.derive_aliases --write`. Re-run it after each
# season's promotions rather than editing by hand.
#
# Mappings are derived by matching fixtures on (date, home goals, away goals)
# within a league-season, not by comparing strings. That distinction matters:
# fuzzy matching would happily collapse `Real Betis`, `Real Sociedad` and
# `Real Valladolid` into one another.
#
# The canonical form follows football-data.co.uk, since those CSVs are the spine
# of the match dataset. A missing alias silently drops rows from a join, so
# resolution is strict and raises on unknown names.

"""

#: Minimum matched fixtures before a mapping is trusted.
MIN_EVIDENCE = 4
#: Share of a team's matched fixtures that must agree on the same counterpart.
MIN_AGREEMENT = 0.9


def derive(
    leagues: list[str], seasons: list[str]
) -> tuple[dict[str, str], list[str]]:
    """Return ``(aliases, warnings)`` mapping Understat names to MatchHistory names."""
    import soccerdata as sd

    # Read football-data.co.uk through our own reader, not soccerdata's: theirs
    # picks encoding by season number and silently loses whole seasons whose
    # files were re-saved with a BOM upstream.
    matches = to_matches(fetch_match_history(leagues, seasons))
    us = (
        sd.Understat(
            leagues=[UNDERSTAT_LEAGUES[c] for c in leagues], seasons=seasons
        )
        .read_team_match_stats()
        .reset_index()
    )

    inverse = {v: k for k, v in UNDERSTAT_LEAGUES.items()}
    mh = matches.assign(league=matches["League"], season=matches["Season"], _date=matches["Date"])
    us = us.assign(
        league=us["league"].map(inverse),
        season=us["season"].astype(str),
        _date=pd.to_datetime(us["date"]).dt.normalize(),
    )

    key = ["league", "season", "_date", "_hg", "_ag"]
    mh_k = mh.assign(
        _hg=mh["FTHG"],
        _ag=mh["FTAG"],
        home_team=mh["HomeTeam"],
        away_team=mh["AwayTeam"],
    )[[*key, "home_team", "away_team"]]
    us_k = us.assign(_hg=us["home_goals"], _ag=us["away_goals"])[
        [*key, "home_team", "away_team"]
    ]

    # Drop fixture keys that are not unique within their league-season, so a
    # coincidental scoreline collision can never produce a false pairing.
    mh_k = mh_k.drop_duplicates(subset=key, keep=False)
    us_k = us_k.drop_duplicates(subset=key, keep=False)

    paired = mh_k.merge(us_k, on=key, suffixes=("_mh", "_us"))

    votes: dict[str, Counter] = defaultdict(Counter)
    for side in ("home", "away"):
        for us_name, mh_name in zip(
            paired[f"{side}_team_us"], paired[f"{side}_team_mh"], strict=True
        ):
            votes[us_name][mh_name] += 1

    aliases: dict[str, str] = {}
    warnings: list[str] = []
    for us_name, counter in sorted(votes.items()):
        best, count = counter.most_common(1)[0]
        total = sum(counter.values())
        if total < MIN_EVIDENCE:
            warnings.append(f"{us_name!r}: only {total} matched fixtures, skipped")
            continue
        if count / total < MIN_AGREEMENT:
            warnings.append(f"{us_name!r}: ambiguous, candidates {dict(counter)}")
            continue
        if us_name != best:
            aliases[us_name] = best

    return aliases, warnings


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--write", action="store_true", help="Update the alias config.")
    parser.add_argument("--start-season", default="1415")
    parser.add_argument("--end-season", default=None)
    args = parser.parse_args()

    logging.basicConfig(level=logging.INFO, format="%(levelname)s %(message)s")
    log = logging.getLogger("derive_aliases")

    seasons = season_labels(args.start_season, args.end_season)
    aliases, warnings = derive(sorted(UNDERSTAT_LEAGUES), seasons)

    print(f"\n=== {len(aliases)} aliases derived ===")
    for k, v in aliases.items():
        print(f"  {k:32s} -> {v}")

    if warnings:
        print(f"\n=== {len(warnings)} need manual review ===")
        for w in warnings:
            print(f"  {w}")

    if args.write:
        config = yaml.safe_load(ALIAS_CONFIG.read_text(encoding="utf-8")) or {}
        config["understat"] = dict(sorted(aliases.items()))
        ALIAS_CONFIG.write_text(
            HEADER + yaml.safe_dump(config, sort_keys=True, allow_unicode=True),
            encoding="utf-8",
        )
        log.info("Wrote %d aliases to %s", len(aliases), ALIAS_CONFIG)
    else:
        print("\n(dry run -- pass --write to update the config)")


if __name__ == "__main__":
    main()
