"""Derive team-name aliases by matching fixtures, not by matching strings.

Fuzzy string matching is the obvious approach and a bad one: ``Real Betis`` and
``Real Madrid`` are close neighbours, and a single wrong mapping silently
corrupts every join downstream.

Instead this matches on what the two sources agree about -- the fixtures
themselves. Within one league-season, a ``(date, home goals, away goals)``
triple almost always identifies exactly one match. Joining on that triple pairs
the two sources' names for the same club directly, with no guessing.

A name is only accepted when the evidence is unambiguous: it must appear in
several matched fixtures and agree in nearly all of them. Anything weaker is
reported for a human to resolve rather than written out.

Two sources need resolving against football-data's canonical names:
``understat`` (player statistics) and ``fbref`` (the forward fixture schedule).
Both are derived the same way, because both publish results we can match on.

Run with::

    python -m pipelines.derive_aliases
    python -m pipelines.derive_aliases --source fbref --write
"""

from __future__ import annotations

import argparse
import logging
import sys
from collections import Counter, defaultdict
from pathlib import Path

import pandas as pd
import yaml

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))

from footballml.data import PROCESSED_DIR  # noqa: E402
from footballml.entities.teams import ALIAS_CONFIG, load_aliases  # noqa: E402
from footballml.ingest.matchhistory import fetch_match_history, to_matches  # noqa: E402
from footballml.ingest.understat import UNDERSTAT_LEAGUES, season_labels  # noqa: E402

HEADER = """\
# Canonical team names and their per-source aliases.
#
# GENERATED by `python -m pipelines.derive_aliases --write`. Re-run it after each
# season's promotions rather than editing by hand.
#
# Mappings are derived by matching fixtures on (date, home goals, away goals)
# within a league-season, not by comparing strings. That distinction matters:
# fuzzy matching would happily collapse `Real Betis`, `Real Sociedad` and
# `Real Valladolid` into one another.
#
# The canonical form follows football-data.co.uk, since those CSVs are the spine
# of the match dataset. A missing alias silently drops rows from a join, so
# resolution is strict and raises on unknown names.

"""

#: Minimum matched fixtures before a mapping is trusted.
MIN_EVIDENCE = 4
#: Share of a team's matched fixtures that must agree on the same counterpart.
MIN_AGREEMENT = 0.9


#: The key that identifies one fixture in both sources.
_KEY = ["league", "season", "_date", "_hg", "_ag"]

#: FBref writes scores with an en-dash ("4–2"), not a hyphen. Splitting on "-"
#: matches nothing and silently drops every fixture, which reads as "no results
#: found" rather than as a parsing bug, so accept any dash-like character.
_SCORE = r"(\d+)\s*[-‐‑‒–—―]\s*(\d+)"


def _read_understat(leagues: list[str], seasons: list[str]) -> pd.DataFrame:
    """Understat results, keyed for matching."""
    import soccerdata as sd

    us = (
        sd.Understat(leagues=[UNDERSTAT_LEAGUES[c] for c in leagues], seasons=seasons)
        .read_team_match_stats()
        .reset_index()
    )
    inverse = {v: k for k, v in UNDERSTAT_LEAGUES.items()}
    return us.assign(
        league=us["league"].map(inverse),
        season=us["season"].astype(str),
        _date=pd.to_datetime(us["date"]).dt.normalize(),
        _hg=us["home_goals"],
        _ag=us["away_goals"],
    )[[*_KEY, "home_team", "away_team"]]


def _read_fbref(leagues: list[str], seasons: list[str]) -> pd.DataFrame:
    """FBref's season schedule, keyed for matching.

    Only played fixtures carry a score, and only played fixtures can be matched
    -- which is the point: the unplayed ones are what we want the aliases *for*.
    """
    import soccerdata as sd

    sched = (
        sd.FBref(leagues=[UNDERSTAT_LEAGUES[c] for c in leagues], seasons=seasons)
        .read_schedule()
        .reset_index()
    )
    inverse = {v: k for k, v in UNDERSTAT_LEAGUES.items()}

    # Scores come as "4–2" with an en-dash, not a hyphen. Splitting on "-" finds
    # nothing and silently drops every fixture, so match any dash character.
    goals = sched["score"].astype(str).str.extract(_SCORE)
    return sched.assign(
        league=sched["league"].map(inverse),
        season=sched["season"].astype(str),
        _date=pd.to_datetime(sched["date"], errors="coerce").dt.normalize(),
        _hg=pd.to_numeric(goals[0], errors="coerce"),
        _ag=pd.to_numeric(goals[1], errors="coerce"),
    ).dropna(subset=["_hg", "_ag", "_date"])[[*_KEY, "home_team", "away_team"]]


READERS = {"understat": _read_understat, "fbref": _read_fbref}

#: EA club names are derived from our own built ratings, not fetched.
PLAYER_RATINGS = PROCESSED_DIR / "player_ratings.csv"


def derive(
    source: str, leagues: list[str], seasons: list[str]
) -> tuple[dict[str, str], list[str]]:
    """Return ``(aliases, warnings)`` mapping ``source`` names to canonical ones."""
    # Read football-data.co.uk through our own reader, not soccerdata's: theirs
    # picks encoding by season number and silently loses whole seasons whose
    # files were re-saved with a BOM upstream.
    matches = to_matches(fetch_match_history(leagues, seasons))
    mh = matches.assign(
        league=matches["League"],
        season=matches["Season"],
        _date=matches["Date"],
        _hg=matches["FTHG"],
        _ag=matches["FTAG"],
        home_team=matches["HomeTeam"],
        away_team=matches["AwayTeam"],
    )[[*_KEY, "home_team", "away_team"]]

    other = READERS[source](leagues, seasons)

    # Drop fixture keys that are not unique within their league-season, so a
    # coincidental scoreline collision can never produce a false pairing.
    mh = mh.drop_duplicates(subset=_KEY, keep=False)
    other = other.drop_duplicates(subset=_KEY, keep=False)

    paired = mh.merge(other, on=_KEY, suffixes=("_mh", "_other"))

    votes: dict[str, Counter] = defaultdict(Counter)
    for side in ("home", "away"):
        for name, canonical in zip(
            paired[f"{side}_team_other"], paired[f"{side}_team_mh"], strict=True
        ):
            votes[name][canonical] += 1

    return _resolve(votes, unit="matched fixtures")


def _resolve(
    votes: dict[str, Counter], unit: str, min_evidence: int = MIN_EVIDENCE
) -> tuple[dict[str, str], list[str]]:
    """Turn votes into aliases, keeping only the well-evidenced, agreed ones.

    Shared by both sources so one cannot drift to a looser bar than the other.
    """
    aliases: dict[str, str] = {}
    warnings: list[str] = []
    for name, counter in sorted(votes.items()):
        best, count = counter.most_common(1)[0]
        total = sum(counter.values())
        if total < min_evidence:
            warnings.append(f"{name!r}: only {total} {unit}, skipped")
            continue
        if count / total < MIN_AGREEMENT:
            warnings.append(f"{name!r}: ambiguous, candidates {dict(counter)}")
            continue
        if name != best:
            aliases[name] = best

    return aliases, warnings


def derive_sofifa(seasons: list[str] | None = None) -> tuple[dict[str, str], list[str]]:
    """EA club names to canonical ones, by which players they share.

    EA publishes no fixtures, so the date-and-scoreline matching the other
    sources use has nothing to work with. Squads do the same job: a club is the
    one its players play for. Within a single season the two labels describe the
    same squad, so agreement is near-total and a disagreement is a real transfer
    rather than a naming difference.

    String similarity is deliberately not used. It would read "Real Betis",
    "Real Sociedad" and "Real Valladolid" as near-identical, which is exactly
    the collapse this project avoids elsewhere -- and the names that actually
    need mapping ("1. FSV Mainz 05" to "Mainz 05", "FC Bayern München" to
    "Bayern Munich") are not the ones string similarity finds easiest.

    Clubs outside the big five -- Ajax, Sporting, Olympiacos -- appear only
    through the odd player who moved mid-season, so they fall under
    `MIN_EVIDENCE` and are skipped rather than mapped to whichever club happened
    to sign one.
    """
    ratings = pd.read_csv(PLAYER_RATINGS, low_memory=False)
    rated = ratings[ratings["rated"].fillna(False).astype(bool)]
    rated = rated.dropna(subset=["fifa_club", "Team"])
    if seasons:
        rated = rated[rated["Season"].astype(str).isin(seasons)]

    # Vote once per season, not once per player. Pooling thirteen seasons of
    # players lets transfers accumulate against a perfectly good name: Villarreal
    # drew 194 votes for itself and a tail of twenty from players who left, and
    # West Ham fell to 0.88 -- under the bar on leavers alone. Within one season
    # the two labels describe the same squad and agreement runs 95-100%, so each
    # season casts a single vote and the thresholds then measure what they are
    # meant to: whether the *name* maps consistently.
    # `Team` here is Understat's spelling, because that is what the ratings are
    # built from. Every other alias map in this file lands on football-data's,
    # so chain through the understat map rather than leaving EA pointing at a
    # third naming scheme that then needs its own translation downstream.
    to_canonical = load_aliases("understat")

    votes: dict[str, Counter] = defaultdict(Counter)
    for (ea_club, _season), squad in rated.groupby(
        [rated["fifa_club"].astype(str), rated["Season"].astype(str)]
    ):
        counts = squad["Team"].map(lambda t: to_canonical.get(str(t), str(t))).value_counts()
        total = int(counts.sum())
        # Enough players to be a squad rather than a loanee or two -- which is
        # how clubs outside the big five turn up here at all -- and enough of
        # them agreeing to rule out a coincidence.
        if total >= MIN_EVIDENCE and counts.iloc[0] / total >= MIN_AGREEMENT:
            votes[ea_club][str(counts.index[0])] += 1

    # One well-evidenced season is enough. Requiring several would be stricter
    # but wrong: EA renames clubs when it loses a licence -- Inter becomes
    # "Lombardia FC", Lazio "Latium", Atalanta "Bergamo Calcio" -- so the labels
    # that most need mapping are precisely the ones that exist for a single
    # edition. The evidence bar is the within-season agreement above; the count
    # here only guards against a label that never formed a squad at all.
    aliases, warnings = _resolve(votes, unit="well-evidenced seasons", min_evidence=1)

    # Votes alone cannot reach a label whose edition has too few *rated* players
    # to form a squad, which is every label introduced by the newest edition: a
    # season five matchweeks old clears the 450-minute floor for barely a
    # hundred players. Those are the labels that matter most, because a rename
    # arrives with a new edition. Chain them instead -- see `_chain_editions`.
    resolved = {name: counter.most_common(1)[0][0] for name, counter in votes.items()}
    chained, chain_warnings = _chain_editions(
        resolved, wanted=set(rated["fifa_club"].astype(str))
    )
    for name, canonical in chained.items():
        if name != canonical:
            aliases[name] = canonical
    return dict(sorted(aliases.items())), [*warnings, *chain_warnings]


#: Players two adjacent editions must share before one club is called the other,
#: and the share of them that must agree.
#:
#: Both are looser than the within-season bars, and deliberately. A squad is the
#: same squad within one season, so agreement there runs 95-100%; between
#: editions a real summer intervenes and the overlap is 57-83% even for clubs
#: that plainly did not change. Holding the within-season bar here would reject
#: every rename it exists to catch.
CHAIN_EVIDENCE_MIN = 4
CHAIN_AGREEMENT = 0.5


def _chain_editions(
    resolved: dict[str, str], wanted: set[str]
) -> tuple[dict[str, str], list[str]]:
    """Resolve an edition's new club labels through the edition before it.

    EA renames a club the season it loses the licence, so the label that needs
    mapping appears for the first time in the newest export -- the one whose
    season has barely started and therefore has almost no rated players to vote
    with. In 2026/27, 181 rated player-seasons had to speak for the whole of
    Serie A, and the result was that 18 of Napoli's 21 players read as having
    *left* for "SSC Napoli", which is Napoli.

    No ratings are needed to fix it. Two editions a year apart share most of
    their squads, so the club a label's players were at last edition names it:
    `SSC Napoli` is `Napoli`, `Bergamo Calcio` is `Atalanta`, `Latium` is
    `Lazio`. Chaining newest-to-oldest then lands every label on a canonical
    name the votes already established.

    Players are identified by name within EA, not across sources, so this does
    not depend on the performance-source matching at all. A name that is not
    unique within an edition is dropped rather than guessed at.

    Each **pair** of editions casts one vote, for the same reason each season
    does in :func:`derive_sofifa`: pooling every player across twelve pairs
    lets a decade of loans and transfers out-vote the club itself. Wigan drew
    106 for Wigan and 150 spread over sixty-odd other clubs, none of them with
    more than seven -- a clear answer that a pooled share of 0.42 called
    ambiguous.

    Args:
        resolved: EA club label to canonical name, from the season votes --
            including the labels that map to themselves, which the alias map
            itself omits.
        wanted: The labels worth reporting on. The EA database carries every
            club on earth and almost none of them can or should resolve to a
            big-five canonical name, so a warning for each would bury the few
            that matter.

    Returns:
        ``(resolved, warnings)`` -- the input plus every label the chain could
        reach, and a note for each wanted label it could not.
    """
    from footballml.players.fifa import load_fifa

    fifa = load_fifa()
    fifa["Season"] = fifa["Season"].astype(str)
    key = "_norm" if "_norm" in fifa.columns else "fifa_name"

    # Name to club, per edition. A name carried by two players in one edition
    # identifies neither, so it is dropped from both sides of every pairing.
    by_season: dict[str, dict[str, str]] = {}
    for season, edition in fifa.groupby("Season"):
        names = edition.dropna(subset=[key, "fifa_club"])
        counts = names[key].value_counts()
        unique = names[names[key].isin(counts[counts == 1].index)]
        by_season[str(season)] = dict(
            zip(unique[key].astype(str), unique["fifa_club"].astype(str), strict=True)
        )

    seasons = sorted(by_season)
    previous: dict[str, Counter] = defaultdict(Counter)
    for newer, older in zip(seasons[1:], seasons[:-1], strict=True):
        before = by_season[older]
        pair: dict[str, Counter] = defaultdict(Counter)
        for name, club in by_season[newer].items():
            if (was := before.get(name)) is not None:
                pair[club][was] += 1
        for club, counter in pair.items():
            was, count = counter.most_common(1)[0]
            total = sum(counter.values())
            if total >= CHAIN_EVIDENCE_MIN and count / total >= CHAIN_AGREEMENT:
                previous[club][was] += 1

    out = dict(resolved)
    warnings: list[str] = []
    # Newest edition first, so a label introduced two editions ago is reached
    # through the one in between rather than having to survive the whole gap.
    for season in reversed(seasons):
        for club in sorted(set(by_season[season].values())):
            if club in out:
                continue
            counter = previous.get(club)
            was = counter.most_common(1)[0][0] if counter else None
            if was is not None and was in out:
                out[club] = out[was]
            elif club in wanted and was != club:
                # A label that chains to itself is simply a club we have no
                # canonical name for -- Benfica, Shakhtar, Vancouver -- which is
                # the normal state of most of the EA database and not a failure.
                # What is worth reporting is a *rename* the chain could not
                # follow back to a name we know.
                warnings.append(
                    f"{club!r}: chains to {was!r}, itself unresolved"
                    if was
                    else f"{club!r}: no edition before it shares a squad"
                )
    return out, warnings


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--write", action="store_true", help="Update the alias config.")
    parser.add_argument(
        "--source", default="understat", choices=[*sorted(READERS), "sofifa"],
        help="Which source's names to resolve against football-data's.",
    )
    parser.add_argument("--start-season", default="1415")
    parser.add_argument("--end-season", default=None)
    args = parser.parse_args()

    logging.basicConfig(level=logging.INFO, format="%(levelname)s %(message)s")
    log = logging.getLogger("derive_aliases")

    seasons = season_labels(args.start_season, args.end_season)
    if args.source == "sofifa":
        # EA has no fixtures to match on; its clubs are resolved by the players
        # they share with ours. See `derive_sofifa`.
        aliases, warnings = derive_sofifa(seasons)
    else:
        aliases, warnings = derive(args.source, sorted(UNDERSTAT_LEAGUES), seasons)

    print(f"\n=== {len(aliases)} aliases derived ===")
    for k, v in aliases.items():
        print(f"  {k:32s} -> {v}")

    if warnings:
        print(f"\n=== {len(warnings)} need manual review ===")
        for w in warnings:
            print(f"  {w}")

    if args.write:
        config = yaml.safe_load(ALIAS_CONFIG.read_text(encoding="utf-8")) or {}
        existing = config.get(args.source) or {}

        # Merge rather than replace. A newly promoted club has only a handful of
        # played matches, so it falls under MIN_EVIDENCE and cannot be derived
        # until it has a season behind it -- but its fixtures still need
        # resolving *now*. Replacing would silently delete the hand-written
        # entry that covers the gap, and a missing alias drops rows from a join.
        kept = {k: v for k, v in existing.items() if k not in aliases}
        if kept:
            log.info(
                "Keeping %d existing %s alias(es) not re-derived this run: %s",
                len(kept), args.source, ", ".join(sorted(kept)),
            )
        config[args.source] = dict(sorted({**existing, **aliases}.items()))

        ALIAS_CONFIG.write_text(
            HEADER + yaml.safe_dump(config, sort_keys=True, allow_unicode=True),
            encoding="utf-8",
        )
        log.info(
            "Wrote %d %s aliases to %s", len(config[args.source]), args.source, ALIAS_CONFIG
        )
    else:
        print("\n(dry run -- pass --write to update the config)")


if __name__ == "__main__":
    main()
