"""Derive team-name aliases by matching fixtures, not by matching strings.

Fuzzy string matching is the obvious approach and a bad one: ``Real Betis`` and
``Real Madrid`` are close neighbours, and a single wrong mapping silently
corrupts every join downstream.

Instead this matches on what the two sources agree about -- the fixtures
themselves. Within one league-season, a ``(date, home goals, away goals)``
triple almost always identifies exactly one match. Joining on that triple pairs
the two sources' names for the same club directly, with no guessing.

A name is only accepted when the evidence is unambiguous: it must appear in
several matched fixtures and agree in nearly all of them. Anything weaker is
reported for a human to resolve rather than written out.

Two sources need resolving against football-data's canonical names:
``understat`` (player statistics) and ``fbref`` (the forward fixture schedule).
Both are derived the same way, because both publish results we can match on.

Run with::

    python -m pipelines.derive_aliases
    python -m pipelines.derive_aliases --source fbref --write
"""

from __future__ import annotations

import argparse
import logging
import sys
from collections import Counter, defaultdict
from pathlib import Path

import pandas as pd
import yaml

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))

from footballml.entities.teams import ALIAS_CONFIG  # noqa: E402
from footballml.ingest.matchhistory import fetch_match_history, to_matches  # noqa: E402
from footballml.ingest.understat import UNDERSTAT_LEAGUES, season_labels  # noqa: E402

HEADER = """\
# Canonical team names and their per-source aliases.
#
# GENERATED by `python -m pipelines.derive_aliases --write`. Re-run it after each
# season's promotions rather than editing by hand.
#
# Mappings are derived by matching fixtures on (date, home goals, away goals)
# within a league-season, not by comparing strings. That distinction matters:
# fuzzy matching would happily collapse `Real Betis`, `Real Sociedad` and
# `Real Valladolid` into one another.
#
# The canonical form follows football-data.co.uk, since those CSVs are the spine
# of the match dataset. A missing alias silently drops rows from a join, so
# resolution is strict and raises on unknown names.

"""

#: Minimum matched fixtures before a mapping is trusted.
MIN_EVIDENCE = 4
#: Share of a team's matched fixtures that must agree on the same counterpart.
MIN_AGREEMENT = 0.9


#: The key that identifies one fixture in both sources.
_KEY = ["league", "season", "_date", "_hg", "_ag"]

#: FBref writes scores with an en-dash ("4–2"), not a hyphen. Splitting on "-"
#: matches nothing and silently drops every fixture, which reads as "no results
#: found" rather than as a parsing bug, so accept any dash-like character.
_SCORE = r"(\d+)\s*[-‐‑‒–—―]\s*(\d+)"


def _read_understat(leagues: list[str], seasons: list[str]) -> pd.DataFrame:
    """Understat results, keyed for matching."""
    import soccerdata as sd

    us = (
        sd.Understat(leagues=[UNDERSTAT_LEAGUES[c] for c in leagues], seasons=seasons)
        .read_team_match_stats()
        .reset_index()
    )
    inverse = {v: k for k, v in UNDERSTAT_LEAGUES.items()}
    return us.assign(
        league=us["league"].map(inverse),
        season=us["season"].astype(str),
        _date=pd.to_datetime(us["date"]).dt.normalize(),
        _hg=us["home_goals"],
        _ag=us["away_goals"],
    )[[*_KEY, "home_team", "away_team"]]


def _read_fbref(leagues: list[str], seasons: list[str]) -> pd.DataFrame:
    """FBref's season schedule, keyed for matching.

    Only played fixtures carry a score, and only played fixtures can be matched
    -- which is the point: the unplayed ones are what we want the aliases *for*.
    """
    import soccerdata as sd

    sched = (
        sd.FBref(leagues=[UNDERSTAT_LEAGUES[c] for c in leagues], seasons=seasons)
        .read_schedule()
        .reset_index()
    )
    inverse = {v: k for k, v in UNDERSTAT_LEAGUES.items()}

    # Scores come as "4–2" with an en-dash, not a hyphen. Splitting on "-" finds
    # nothing and silently drops every fixture, so match any dash character.
    goals = sched["score"].astype(str).str.extract(_SCORE)
    return sched.assign(
        league=sched["league"].map(inverse),
        season=sched["season"].astype(str),
        _date=pd.to_datetime(sched["date"], errors="coerce").dt.normalize(),
        _hg=pd.to_numeric(goals[0], errors="coerce"),
        _ag=pd.to_numeric(goals[1], errors="coerce"),
    ).dropna(subset=["_hg", "_ag", "_date"])[[*_KEY, "home_team", "away_team"]]


READERS = {"understat": _read_understat, "fbref": _read_fbref}


def derive(
    source: str, leagues: list[str], seasons: list[str]
) -> tuple[dict[str, str], list[str]]:
    """Return ``(aliases, warnings)`` mapping ``source`` names to canonical ones."""
    # Read football-data.co.uk through our own reader, not soccerdata's: theirs
    # picks encoding by season number and silently loses whole seasons whose
    # files were re-saved with a BOM upstream.
    matches = to_matches(fetch_match_history(leagues, seasons))
    mh = matches.assign(
        league=matches["League"],
        season=matches["Season"],
        _date=matches["Date"],
        _hg=matches["FTHG"],
        _ag=matches["FTAG"],
        home_team=matches["HomeTeam"],
        away_team=matches["AwayTeam"],
    )[[*_KEY, "home_team", "away_team"]]

    other = READERS[source](leagues, seasons)

    # Drop fixture keys that are not unique within their league-season, so a
    # coincidental scoreline collision can never produce a false pairing.
    mh = mh.drop_duplicates(subset=_KEY, keep=False)
    other = other.drop_duplicates(subset=_KEY, keep=False)

    paired = mh.merge(other, on=_KEY, suffixes=("_mh", "_other"))

    votes: dict[str, Counter] = defaultdict(Counter)
    for side in ("home", "away"):
        for name, canonical in zip(
            paired[f"{side}_team_other"], paired[f"{side}_team_mh"], strict=True
        ):
            votes[name][canonical] += 1

    aliases: dict[str, str] = {}
    warnings: list[str] = []
    for name, counter in sorted(votes.items()):
        best, count = counter.most_common(1)[0]
        total = sum(counter.values())
        if total < MIN_EVIDENCE:
            warnings.append(f"{name!r}: only {total} matched fixtures, skipped")
            continue
        if count / total < MIN_AGREEMENT:
            warnings.append(f"{name!r}: ambiguous, candidates {dict(counter)}")
            continue
        if name != best:
            aliases[name] = best

    return aliases, warnings


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--write", action="store_true", help="Update the alias config.")
    parser.add_argument(
        "--source", default="understat", choices=sorted(READERS),
        help="Which source's names to resolve against football-data's.",
    )
    parser.add_argument("--start-season", default="1415")
    parser.add_argument("--end-season", default=None)
    args = parser.parse_args()

    logging.basicConfig(level=logging.INFO, format="%(levelname)s %(message)s")
    log = logging.getLogger("derive_aliases")

    seasons = season_labels(args.start_season, args.end_season)
    aliases, warnings = derive(args.source, sorted(UNDERSTAT_LEAGUES), seasons)

    print(f"\n=== {len(aliases)} aliases derived ===")
    for k, v in aliases.items():
        print(f"  {k:32s} -> {v}")

    if warnings:
        print(f"\n=== {len(warnings)} need manual review ===")
        for w in warnings:
            print(f"  {w}")

    if args.write:
        config = yaml.safe_load(ALIAS_CONFIG.read_text(encoding="utf-8")) or {}
        existing = config.get(args.source) or {}

        # Merge rather than replace. A newly promoted club has only a handful of
        # played matches, so it falls under MIN_EVIDENCE and cannot be derived
        # until it has a season behind it -- but its fixtures still need
        # resolving *now*. Replacing would silently delete the hand-written
        # entry that covers the gap, and a missing alias drops rows from a join.
        kept = {k: v for k, v in existing.items() if k not in aliases}
        if kept:
            log.info(
                "Keeping %d existing %s alias(es) not re-derived this run: %s",
                len(kept), args.source, ", ".join(sorted(kept)),
            )
        config[args.source] = dict(sorted({**existing, **aliases}.items()))

        ALIAS_CONFIG.write_text(
            HEADER + yaml.safe_dump(config, sort_keys=True, allow_unicode=True),
            encoding="utf-8",
        )
        log.info(
            "Wrote %d %s aliases to %s", len(config[args.source]), args.source, ALIAS_CONFIG
        )
    else:
        print("\n(dry run -- pass --write to update the config)")


if __name__ == "__main__":
    main()
